services:
    server:
        build:
            context: .
        ports:
            - 8000:8000
        env_file:
            - .env
        volumes:
            - .:/app
            - models:/root/.cache/huggingface/hub:rw
        command:
            [
                "uvicorn",
                "--app-dir",
                "src",
                "main:app",
                "--host",
                "0.0.0.0",
                "--port",
                "$PORT",
                "--reload",
            ]
volumes:
    models:
